### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by yaolp123** [haarsh09/Brain-Tumor-Classification#1]
Dear authors: 
    Recently I  have looking your this project and feel interested in it ! could have a dataset of this project.  Thanks a lot.

Best regards.

**Comment by haarsh09** [comment]
You can download it from kaggle.

**Comment by yaolp123** [comment]
Dear authors:
  I am pleased to hear from your reply. But which kind of the dataset I would download?

**Comment by haarsh09** [comment]
> Dear authors: I am pleased to hear from your reply. But which kind of the dataset I would download?

Go to kaggle and just type brain tumor dataset.
